- name: Launch instances on OpenStack
  hosts: localhost
  gather_facts: false

  vars:
    count: 2
    cluster_state: present

  tasks:
    - name: Create ansible security group
      os_security_group:
        state: present
        name: ansible
        verify: false
    - name: Create a rule to allow SSH connections
      os_security_group_rule:
        security_group: ansible
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
        verify: false
    - name: Create webserver security group
      os_security_group:
        state: present
        name: webserver
        verify: false
    - name: Create rule to allow http connections
      os_security_group_rule:
        security_group: webserver
        protocol: tcp
        port_range_min: 80
        port_range_max: 80
        remote_ip_prefix: 0.0.0.0/0
        verify: false
     
    - name: Deploy an instance
      os_server:
        state: "{{ cluster_state }}"
        name: spark_node{{ item }}
        image: Ubuntu 18.04
        key_name: ansible_key
        timeout: 200
        flavor: ssc.xsmall
        network: UPPMAX 2020/1-2 Internal IPv4 Network
        security_groups: default,ansible,webserver,wz_test
        verify: false
      register: nova_cookbook
      with_sequence:        
        count={{ count }}
      tags: 
        - delete_cluster

    - name: Add instance to Inventory      
      add_host: name="{{ item.server.name }}" groups=webservers         	
                ansible_ssh_host="{{ item.server.accessIPv4 }}"    
      with_items: "{{ nova_cookbook.results }}"

- name: Wait for port 22 to be ready
  hosts: webservers
  gather_facts: False
  tasks:
    - local_action: wait_for port=22 host="{{ ansible_ssh_host }}"  search_regex=OpenSSH delay=10

- hosts: webservers
  remote_user: ubuntu
  become: yes
  gather_facts: no
  tasks:
    - name: 'install python minimal'
      raw:  sudo apt-get -y update && sudo apt-get -y install python-minimal
