#!/bin/bash

IP="0.0.0.0"
PORT="5000"
ADDRESS="http://$IP:$PORT"

if [ "$1" = "start" ]
then 
    curl -X POST "$ADDRESS/start"
elif [ "$1" = "status" ]
then
    curl -X GET "$ADDRESS/status"
elif [ "$1" = "resize" ]
then
    curl -X POST "$ADDRESS/resize" -d "$2"
elif [ "$1" = "inject" ]
then
    curl -X POST "$ADDRESS/inject" -F "$2=@$2"
fi
