#!/bin/bash

IP="${ANSIBLE_MASTER_IP:-0.0.0.0}"
PORT="5000"
ADDRESS="http://$IP:$PORT/api"

if [ "$1" = "start" ]
then 
    curl -X POST "$ADDRESS/start"
elif [ "$1" = "shutdown" ]
then
    curl -X POST "$ADDRESS/shutdown"
elif [ "$1" = "status" ]
then
    curl -X GET "$ADDRESS/status"
elif [ "$1" = "resize" ]
then
    curl -X POST "$ADDRESS/resize" -d "$2"
elif [ "$1" = "inject" ]
then
    NAME=$(basename "$2")
    curl -X POST "$ADDRESS/inject" -F "$NAME=@$2"
elif [ "$1" = "set-ip" ]
    export ANSIBLE_MASTER_IP="$2"
fi
